from __future__ import annotations

from pathlib import Path

import markdown

from jinja2 import Environment
from jinja2 import FileSystemLoader

from schemas.report_schema import ExecutiveReport

class ReportRenderer:
    """
    Enterprise Report Renderer

    Responsibilities
    ----------------
    - ExecutiveReport → Markdown
    - ExecutiveReport → HTML
    - ExecutiveReport → PDF (later)
    """
    
    def to_markdown(
        self,
        report: ExecutiveReport,
    ) -> str:

        markdown = f"""# {report.header.title}

    **Company:** {report.header.company_name}

    **Dataset:** {report.header.dataset_name}

    **Generated:** {report.header.generated_at}

    ---

    # Executive Summary

    {report.executive_summary}

    ---

    # Business Health

    {report.business.health}

    ---

    # KPI Highlights

    | KPI | Value |
    |------|------:|
    | Revenue Growth | {report.kpis.revenue_growth:.2f}% |
    | Profit Margin | {report.kpis.profit_margin:.2f}% |
    | Customer Satisfaction | {report.kpis.customer_satisfaction:.2f} |
    | Customer Churn | {report.kpis.customer_churn:.2f}% |

    ---

    # Key Findings

    """

        for finding in report.business.key_findings:
            markdown += f"- {finding}\n"

        markdown += "\n---\n\n# Risks\n\n"

        for risk in report.risks.critical:
            markdown += f"- {risk}\n"

        markdown += "\n---\n\n# Opportunities\n\n"

        for opportunity in report.opportunities.opportunities:
            markdown += f"- {opportunity}\n"

        markdown += "\n---\n\n# Strategic Recommendations\n\n"

        for recommendation in report.recommendations.strategic:
            markdown += f"- {recommendation}\n"

        markdown += f"""

    ---

    # Executive Decision

    {report.executive_decision}

    ---

    _Report generated by {report.footer.generated_by}_
    """

        return markdown
    
    
    def to_html(
        self,
        report: ExecutiveReport,
    ) -> str:

        markdown_report = self.to_markdown(
            report
        )

        html_body = markdown.markdown(

            markdown_report,

            extensions=[

                "tables",

                "fenced_code",
            ]
        )

        template_dir = (
            Path(__file__)
            .parent.parent
            / "templates"
        )

        env = Environment(

            loader=FileSystemLoader(
                template_dir
            )
        )

        template = env.get_template(
            "executive_report.html"
        )

        html = template.render(

            title=report.header.title,

            body=html_body,
        )

        return html