from __future__ import annotations

from datetime import datetime
from typing import Any

from loguru import logger


class ReportService:
    """
    Enterprise Executive Report Service

    Responsibilities
    ----------------
    - Executive Summary Generation
    - KPI Reporting
    - Insight Reporting
    - Recommendation Reporting
    - Business Health Assessment
    - Board-Level Reporting

    Used By
    -------
    - Report Agent
    - BI Workflow
    - Dashboard Export
    - PDF Generator
    """

    def generate_report(
        self,
        dataset_name: str,
        kpis: dict[str, Any],
        insights: list[str],
        recommendations: list[str],
        health_score: dict[str, Any],
        business_analysis: dict[str, Any]
    ) -> str:

        logger.info(
            "Generating executive report"
        )

        executive_decision = business_analysis.get(
            "executive_decision",
            {}
        )

        business_readiness = business_analysis.get(
            "business_readiness",
            {}
        )

        report_sections: list[str] = []

        # =====================================
        # HEADER
        # =====================================

        report_sections.append(
            "=" * 70
        )

        report_sections.append(
            "AI BUSINESS INTELLIGENCE REPORT"
        )

        report_sections.append(
            "=" * 70
        )

        report_sections.append(
            f"Dataset: {dataset_name}"
        )

        report_sections.append(
            f"Generated At: "
            f"{datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}"
        )

        report_sections.append("")

        # =====================================
        # EXECUTIVE SUMMARY
        # =====================================

        report_sections.append(
            "EXECUTIVE SUMMARY"
        )

        report_sections.append(
            "-" * 70
        )

        report_sections.append(
            f"""
This report was automatically generated by the
AI Business Intelligence Copilot.

The dataset '{dataset_name}' was analyzed to identify
key business metrics, operational trends,
performance indicators, anomalies,
opportunities, and strategic recommendations.
"""
        )

        report_sections.append("")

        # =====================================
        # KPI SECTION
        # =====================================

        report_sections.append(
            "KEY PERFORMANCE INDICATORS"
        )

        report_sections.append(
            "-" * 70
        )

        if kpis:

            financial = kpis.get(
                "financial",
                {}
            )

            category = kpis.get(
                "category",
                {}
            )

            operational = kpis.get(
                "operational",
                {}
            )

            quality = kpis.get(
                "quality",
                {}
            )

            report_sections.extend([

                f"Total Revenue         : ${financial.get('total_revenue',0):,.0f}",

                f"Average Revenue       : ${financial.get('average_revenue',0):,.2f}",

                f"Maximum Revenue       : ${financial.get('max_revenue',0):,.2f}",

                f"Minimum Revenue       : ${financial.get('min_revenue',0):,.2f}",

                f"Total Orders          : {financial.get('total_orders',0):,}",

                f"Average Order Value   : ${financial.get('average_order_value',0):,.2f}",

                f"Top Category          : {category.get('top_category','N/A')}",

                f"Units Sold            : {operational.get('total_quantity',0):,}",

                f"Quality Score         : {quality.get('quality_score',0)}%",

                f"Missing Cells         : {quality.get('missing_cells',0)}",

                f"Duplicate Rows        : {quality.get('duplicate_rows',0)}",

                "",   # blank line

                f"Business Health       : {health_score.get('business_health_score',0)}/100"
            ])

        else:

            report_sections.append(
                "No KPI metrics available."
            )

        report_sections.append("")

        # =====================================
        # INSIGHTS
        # =====================================

        report_sections.append(
            "BUSINESS INSIGHTS"
        )

        report_sections.append(
            "-" * 70
        )

        if insights:

            for index, insight in enumerate(
                insights,
                start=1
            ):

                report_sections.append(
                    f"{index}. {insight}"
                )

        else:

            report_sections.append(
                "No significant insights detected."
            )

        report_sections.append("")

        # =====================================
        # RECOMMENDATIONS
        # =====================================

        report_sections.append(
            "STRATEGIC RECOMMENDATIONS"
        )

        report_sections.append(
            "-" * 70
        )

        if recommendations:

            for index, recommendation in enumerate(
                recommendations,
                start=1
            ):

                report_sections.append(
                    f"{index}. {recommendation}"
                )

        else:

            report_sections.append(
                "No recommendations generated."
            )

        report_sections.append("")

        # =====================================
        # BUSINESS HEALTH SCORE
        # =====================================

        report_sections.append(
            "BUSINESS HEALTH ASSESSMENT"
        )

        report_sections.append(
            "-" * 70
        )

        health = health_score.get(
            "business_health_score",
            0
        )

        health_status = health_score.get(
            "status",
            "UNKNOWN"
        )

        report_sections.append(
            f"Business Health Score: "
            f"{health}/100"
        )

        if health >= 80:

            report_sections.append(
                "Assessment: Excellent"
            )

        elif health>= 60:

            report_sections.append(
                "Assessment: Good"
            )

        elif health>= 40:

            report_sections.append(
                "Assessment: Moderate"
            )

        else:

            report_sections.append(
                "Assessment: Needs Attention"
            )

        report_sections.append("")
        
        # =====================================
        # EXECUTIVE DECISION
        # =====================================

        report_sections.append(
            "EXECUTIVE DECISION"
        )

        report_sections.append(
            "-" * 70
        )

        report_sections.append(
            f"Decision            : {executive_decision.get('decision', 'N/A')}"
        )

        report_sections.append(
            f"Priority            : {executive_decision.get('priority', 'N/A')}"
        )

        report_sections.append(
            f"Confidence          : {executive_decision.get('confidence', 0)}%"
        )

        report_sections.append(
            f"Expected ROI        : {executive_decision.get('expected_roi', 'N/A')}"
        )

        report_sections.append(
            f"Reason              : {executive_decision.get('reason', 'N/A')}"
        )

        report_sections.append("")
        
        # =====================================
        # BUSINESS READINESS
        # =====================================

        report_sections.append(
            "BUSINESS READINESS"
        )

        report_sections.append(
            "-" * 70
        )

        report_sections.append(
            f"Status              : {business_readiness.get('status', 'N/A')}"
        )

        report_sections.append(
            f"Deployment          : {business_readiness.get('deployment', 'N/A')}"
        )

        report_sections.append(
            f"Overall Score       : {business_readiness.get('score', 0)}/100"
        )

        report_sections.append(
            f"Reason              : {business_readiness.get('reason', 'N/A')}"
        )

        report_sections.append("")

        # =====================================
        # FOOTER
        # =====================================

        report_sections.append(
            "=" * 70
        )

        report_sections.append(
            "Generated by AI BI Copilot"
        )

        report_sections.append(
            "Confidential Business Intelligence Report"
        )

        report_sections.append(
            "=" * 70
        )

        report = "\n".join(
            report_sections
        )

        logger.success(
            "Executive report generated successfully"
        )

        return report